### ISSUE TITLE
sometimes callbacks not called

### ISSUE THREAD

**Issue by doowb** [npm/inflight#1]
When writing tests for libraries that use `node-glob`, I find that sometimes matches aren't emitted because I'm using the same file path in a bunch of tests. When I remove the `inflight` code from `node-glob` or run the tests individually, they all pass.

I saw that you made [this commit](https://github.com/npm/inflight/commit/32bc5b6e2594fe172952d12c53fcb82ffd21d44d) about a year ago to handle when new callbacks are added. I'm not sure what a fix for this would be (or if it even belongs here).

**Comment by phated** [comment]
Just ran into this while trying to fix some stuff in node-glob per use in glob-stream.

cc @isaacs @othiym23

**Comment by phated** [comment]
I found it!  It's caused by a callback throwing and the inflight keys not being cleaned up.  I'm starting on a test now.

**Comment by isaacs** [comment]
@phated @doowb Is there an issue in node-glob for the behavior as well?  It should not be throwing in any internal functions, so that'd be a weird issue that I'd love to be able to reproduce.

I'm not sure whether "call all functions even if one of them throws" is necessarily the best idea.  Continuing the stack of functions is a breaking semantic change, and catch-and-rethrow obscures the source of the error.

**Comment by phated** [comment]
@isaacs if what I'm seeing is correct, the problem is with someone throwing inside the `on('match')` callback.  My tests were throwing on an assert and it was being swallowed but then other different tests were timing out because the inflight requests weren't cleaned up.

I didn't think that my implementation was proper but I'm not sure how to cleanup on throw and not swallow the error.  Nothing felt quite right as I talked through it with @nrn

**Comment by phated** [comment]
@isaacs actually, this might just be solvable by `try/finally` - let me submit another commit on my open PR

**Comment by phated** [comment]
Updated! https://github.com/npm/inflight/pull/3

**Comment by doowb** [comment]
Using that `try/finally` looks like a good idea because additional callbacks will be resolved.

If I recall correctly, I attempted to wrap my `assert` calls in a try catch inside the callback I was using and that didn't work because if an error from a previous test caused it so none of the callbacks would be called.

**Comment by phated** [comment]
@doowb anything that is zalgo'd will be resolved but the ones that are queued before any execution won't be.  I think this is the least surprising behavior.
